# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5467e54de1b7dacff47dead9ad5c9589a76ed55e6f0ed6e990c7cba8bff3538c9b3899a712f0d8df4e3e3dacece72985f4df5c7122a473b0b9f31a41de4a99ae

test:
  secret_key_base: 75479fc4068477e664f0cf3c7e537d802be917b280c1830b209c802ea11d6adc127f36706eccd0e3eb18e9c684dad0f47b30ced24e82c8bdd9fc55e85932a4a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
